#!/bin/bash

# $1=RULE-NAME, $2=CHAIN $3=PROTOCOL, $4=PORT

#echo "SHUTDOWN $1"

if [ -n "$4" ]; then
	PORTS="-m multiport --dports $4"
	PROTOCOL="-p $3"
else
	PORTS=""
	PROTOCOL=""
fi

iptables -D $2 $PROTOCOL $PORTS -j "la-$1"
iptables -F "la-$1"
iptables -X "la-$1"

ip6tables -D $2 $PROTOCOL $PORTS -j "la-$1"
ip6tables -F "la-$1"
ip6tables -X "la-$1"

